DROP DATABASE IF EXISTS BD_INSTITUTO;
CREATE DATABASE BD_INSTITUTO;
USE BD_INSTITUTO;

CREATE USER 'usuario'@'localhost' IDENTIFIED BY 'password' IF NOT EXISTS;
GRANT ALL PRIVILEGES ON BD_INSTITUTO.*  TO 'usuario'@'localhost';

CREATE TABLE `PROFESOR` (
  `CODIGO_PROFESOR` INT(11) NOT NULL,
  `NOMBRE_PROFESOR` CHAR(20) NOT NULL,
  `APELLIDO1_PROFESOR` CHAR(20) NOT NULL,
  `APELLIDO2_PROFESOR` CHAR(20) NOT NULL,
  `DI_PROFESOR` CHAR(9) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=ISO-8859;


INSERT INTO `PROFESOR` (`CODIGO_PROFESOR`, `NOMBRE_PROFESOR`, `APELLIDO1_PROFESOR`, `APELLIDO2_PROFESOR`, `DI_PROFESOR`) VALUES
(1, 'Carlos', 'Ollero', 'Sanchez', '56233981A'),
(2, 'Joaquin', 'Rosado', 'Fresneda', '12345678B'),
(3, 'Agustin', 'Lozano', 'Iglesias', '66655537K'),
(4, 'Luis Alfonso', 'Sanchez', 'Blanco', '22266654F');


CREATE TABLE `ALUMNO` (
  `CODIGO_ALUMNO` INT(11) NOT NULL,
  `NOMBRE_ALUMNO` CHAR(20) NOT NULL,
  `APELLIDO1_ALUMNO` CHAR(20) NOT NULL,
  `APELLIDO2_ALUMNO` CHAR(20) NOT NULL,
  `DI_ALUMNO` CHAR(9) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=ISO-8859;


CREATE TABLE `ASIGNATURA` (
  `CODIGO_ASIGNATURA` INT(11) NOT NULL,
  `NOMBRE_ASIGNATURA` CHAR(20) NOT NULL,
  `PRECIO_ASIGNATURA` INT(11) NOT NULL,
  `CODIGO_PROFESOR` INT(11) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=ISO-8859;

INSERT INTO `ASIGNATURA` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `PRECIO_ASIGNATURA`, `CODIGO_PROFESOR`) VALUES
(1, 'Programacion', 400, 3),
(2, 'Bases de Datos', 400, 4),
(3, 'Sistemas Informatico', 250, 1),
(4, 'Leng. de Marcas', 200, 2),
(5, 'Ent. de Desarrollo', 200, 2);

CREATE TABLE `MATRICULA` (
  `CURSO_MATRICULA` CHAR(20) NOT NULL,
  `GRUPO_MATRICULA` CHAR(20) NOT NULL
  `CODIGO_ALUMNO` INT(11) NOT NULL,
  `CODIGO_ASIGNATURA` INT(11) NOT NULL,
  `CODIGO_PROFESOR` INT(11) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=ISO-8859;


ALTER TABLE `ALUMNO`
  ADD PRIMARY KEY (`CODIGO_ALUMNO`),
  ADD UNIQUE KEY `DI_ALUMNO` (`DI_ALUMNO`);

ALTER TABLE `ASIGNATURA`
  ADD PRIMARY KEY (`CODIGO_ASIGNATURA`,`CODIGO_PROFESOR`),
  ADD KEY `CODIGO_PROFESOR` (`CODIGO_PROFESOR`);

ALTER TABLE `MATRICULA`
  ADD PRIMARY KEY (`CODIGO_ALUMNO`,`CODIGO_ASIGNATURA`,`CODIGO_PROFESOR`),
  ADD KEY `CODIGO_ASIGNATURA` (`CODIGO_ASIGNATURA`,`CODIGO_PROFESOR`);

ALTER TABLE `PROFESOR`
  ADD PRIMARY KEY (`CODIGO_PROFESOR`),
  ADD UNIQUE KEY `DI_PROFESOR` (`DI_PROFESOR`);

ALTER TABLE `ALUMNO`
  MODIFY `CODIGO_ALUMNO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `ASIGNATURA`
  MODIFY `CODIGO_ASIGNATURA` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

ALTER TABLE `PROFESOR`
  MODIFY `CODIGO_PROFESOR` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

ALTER TABLE `ASIGNATURA`
  ADD CONSTRAINT `ASIGNATURA_ibfk_1` FOREIGN KEY (`CODIGO_PROFESOR`) REFERENCES `PROFESOR` (`CODIGO_PROFESOR`) ON UPDATE CASCADE;

ALTER TABLE `MATRICULA`
  ADD CONSTRAINT `MATRICULA_ibfk_1` FOREIGN KEY (`CODIGO_ALUMNO`) REFERENCES `ALUMNO` (`CODIGO_ALUMNO`) ON UPDATE CASCADE,
  ADD CONSTRAINT `MATRICULA_ibfk_2` FOREIGN KEY (`CODIGO_ASIGNATURA`,`CODIGO_PROFESOR`) REFERENCES `ASIGNATURA` (`CODIGO_ASIGNATURA`, `CODIGO_PROFESOR`) ON UPDATE CASCADE;
COMMIT;

