
/*
CREATED		08/05/2019
MODIFIED	11/05/2019
PROJECT		PRACTICA FINAL JAVA	
MODEL		INSTITUTO
AUTHOR		JOSE VEGA FLORDELIS		
VERSION		1.3.3
DATABASE	MYSQL 5 
*/

DROP DATABASE IF EXISTS BD_INSTITUTO;
CREATE DATABASE BD_INSTITUTO;
USE BD_INSTITUTO;

CREATE TABLE `ALUMNO` (
	`CODIGO_ALUMNO` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE_ALUMNO` CHAR(20) NOT NULL,
	`APELLIDO1_ALUMNO` CHAR(20) NOT NULL,
	`APELLIDO2_ALUMNO` CHAR(20) NOT NULL,
	`DI_ALUMNO` CHAR(9) NOT NULL,
	UNIQUE (`DI_ALUMNO`),
 PRIMARY KEY (`CODIGO_ALUMNO`)) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `PROFESOR` (
	`CODIGO_PROFESOR` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE_PROFESOR` CHAR(20) NOT NULL,
	`APELLIDO1_PROFESOR` CHAR(20) NOT NULL,
	`APELLIDO2_PROFESOR` CHAR(20) NOT NULL,
	`DI_PROFESOR` CHAR(9) NOT NULL,
	UNIQUE (`DI_PROFESOR`),
 PRIMARY KEY (`CODIGO_PROFESOR`)) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ASIGNATURA` (
	`CODIGO_ASIGNATURA` CHAR(20) NOT NULL,
	`NOMBRE_ASIGNATURA` CHAR(20) NOT NULL,
	`PRECIO_ASIGNATURA` CHAR(20) NOT NULL,
	`CODIGO_PROFESOR` INT NOT NULL,
 PRIMARY KEY (`CODIGO_ASIGNATURA`,`CODIGO_PROFESOR`)) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MATRICULA` (
	`CODIGO_MATRICULA` INT NOT NULL AUTO_INCREMENT,
	`CODIGO_ALUMNO` INT NOT NULL,
	`CODIGO_ASIGNATURA` CHAR(20) NOT NULL,
	`NOTA` INT,
 PRIMARY KEY (`CODIGO_MATRICULA`,`CODIGO_ALUMNO`,`CODIGO_ASIGNATURA`)) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `MATRICULA` ADD FOREIGN KEY (`CODIGO_ALUMNO`) REFERENCES `ALUMNO` (`CODIGO_ALUMNO`) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE `ASIGNATURA` ADD FOREIGN KEY (`CODIGO_PROFESOR`) REFERENCES `PROFESOR` (`CODIGO_PROFESOR`) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE `MATRICULA` ADD FOREIGN KEY (`CODIGO_ASIGNATURA`) REFERENCES `ASIGNATURA` (`CODIGO_ASIGNATURA`) ON DELETE  RESTRICT ON UPDATE  RESTRICT;

INSERT INTO `PROFESOR` (`CODIGO_PROFESOR`, `NOMBRE_PROFESOR`, `APELLIDO1_PROFESOR`, `APELLIDO2_PROFESOR`, `DI_PROFESOR`) VALUES
(1, 'Carlos', 'Ollero', 'Sánchez', '56233981A'),
(2, 'Joaquín', 'Rosado', 'Fresneda', '12345678B'),
(3, 'Agustín', 'Lozano', 'Iglesias', '66655537K'),
(4, 'Luis Alfonso', 'Sánchez', 'Blanco', '22266654F');

INSERT INTO `ASIGNATURA` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `PRECIO_ASIGNATURA`, `CODIGO_PROFESOR`) VALUES
(1, 'Programación', 400, 3),
(2, 'Bases de Datos', 400, 4),
(3, 'Sistemas Inf.', 250, 1),
(4, 'Leng. de Marcas', 200, 2),
(5, 'Ent. de Desarrollo', 200, 2);
